### ISSUE TITLE
url scheme must be https

### ISSUE THREAD

**Issue by NerdJeremia** [microsoft/kiota-authentication-azure-go#97]
https://github.com/microsoft/kiota-authentication-azure-go/blob/ddf14e2d8f579f59448df338a94996e293357b60/azure_identity_access_token_provider.go#L81

We migrated to a kiota generated go client for our API in a custom terraform provider and ran into the issue that we can't call our local dev environment running on http with this client. 
Can this be changed to a dynamic configuration instead of being hardcoded?

**Comment by baywet** [comment]
Hi @NerdJeremia,
Thanks for using Kiota and for reporting this.
Can you share more information about the URIs of the API you're calling please?
The reason we hardcoded this and might be reluctant to make it a setting is because it'd make an easy way for people to shoot themselves in the foot and send access token in clear over the wire.
But maybe we could relax the test a little like not requiring HTTPs if the host is "localhost" or "127.0.0.1" or "[::1]". Thoughts ? (granted that the loopback name can also be aliased, and additional loopback addressed can be setup, but this should cover the majority of cases)

**Comment by baywet** [comment]
Thanks for the additional details here, do you think you could submit a pull request to implement the changes?

**Comment by NerdJeremia** [comment]
Sure thing
